CREATE DATABASE querydsl;
CREATE DATABASE querydsl2;
CREATE USER querydsl WITH PASSWORD 'querydsl';
GRANT ALL PRIVILEGES ON DATABASE querydsl TO querydsl;
GRANT ALL PRIVILEGES ON DATABASE querydsl2 TO querydsl;
