# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "querydsl-server"

  # Boot with a GUI so you can see the screen. Good for debugging startup issues. 
  # config.vm.boot_mode = :gui

  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  config.vm.network :forwarded_port, guest: 1521, host: 1521
  config.vm.network :forwarded_port, guest: 30000, host: 30000

  config.vm.synced_folder ".", "/opt/querydsl"

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM
    vb.customize ["modifyvm", :id,
                  "--memory", "1024",
                  "--name", "querydsl-server",
                  "--natdnshostresolver1", "on"]
  end

  config.vbguest.auto_update = false

  config.vm.provision :puppet, :module_path => "modules" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "site.pp"
  end

end
