# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.hostname = "querydsl-server"

  # Boot with a GUI so you can see the screen. Good for debugging startup issues. 
  # config.vm.boot_mode = :gui

  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct: true   # postgresql
  config.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true   # mysql
  config.vm.network :forwarded_port, guest: 1521, host: 1521, auto_correct: true   # oracle
  config.vm.network :forwarded_port, guest: 30000, host: 30000, auto_correct: true # cubrid
  config.vm.network :forwarded_port, guest: 27017, host: 27017, auto_correct: true # mongodb

  config.vm.synced_folder ".", "/opt/querydsl"

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM
    vb.customize ["modifyvm", :id,
                  "--memory", "1024",
                  "--name", "querydsl-server",
                  "--natdnshostresolver1", "on"]
  end

  config.vbguest.auto_update = false

  config.vm.provision "shell", path: "bootstrap.sh"

end
