forge "http://forge.puppetlabs.com"

mod "puppetlabs/apt"
mod "puppetlabs/stdlib"
mod "puppetlabs/java"
mod "puppetlabs/mysql"
mod "puppetlabs/postgresql"

mod "mysqlscript",
  :git => "git://github.com/jstaffans/puppet-mysqlscript.git"

mod "oracle",
  :git => "git://github.com/jstaffans/puppet-oracle.git"

mod "cubrid",
  :git => "git://github.com/jstaffans/puppet-cubrid-demodb.git"

